language: python

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27-dj18-cms32
  - TOX_ENV=py27-dj18-cms31
  - TOX_ENV=py27-dj17-cms32
  - TOX_ENV=py27-dj17-cms31
  - TOX_ENV=py27-dj17-cms30
  - TOX_ENV=py27-dj16-cms32
  - TOX_ENV=py27-dj16-cms31
  - TOX_ENV=py27-dj16-cms30
  - TOX_ENV=py27-dj15-cms30
  - TOX_ENV=py27-dj14-cms30

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
